services:
  - type: web
    name: code-learning-platform
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        value: https://your-app-name.onrender.com